apiVersion: apps/v1
kind: Deployment
metadata:
  name: findmylifepartner-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: findmylifepartner
  template:
    metadata:
      labels:
        app: findmylifepartner
    spec:
      containers:
      - name: findmylifepartner-image
        image: europe-west2-docker.pkg.dev/${{ secrets.GKE_PROJECT }}helloworld-gke:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          limits:
            memory: 512Mi
            cpu: "1"